name: Bug report
description: >-
  Create a report to help us improve
title: '[Bug]: '
labels:
  - bug
body:
  - type: checkboxes
    id: target
    attributes:
      label: What does the bug relate to?
      options:
        - label: Plugin's core
        - label: Debugger
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      placeholder: >-
        1. Go to '...' 2. Click on '....' 3. Scroll down to '....' 4. See error
    validations:
      required: true
  - type: input
    id: vite-version
    attributes:
      label: Vite version
      placeholder: '5.1.0'
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
