name: Feature request
description: >-
  Suggest an idea for this project
title: '[Feature request]: '
labels:
  - feature request
body:
  - type: checkboxes
    id: target
    attributes:
      label: What does the feature request relate to?
      options:
        - label: Plugin's core
        - label: Debugger
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is
      placeholder: Ex. I'm always frustrated when [...]
  - type: textarea
    id: what
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description:
        A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
