name: Setup pnpm
description: Prepare repository and all dependencies

runs:
  using: composite
  steps:
    - uses: actions/checkout@v6
      with:
        persist-credentials: false
    - name: Install pnpm and Node.js
      uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2 # v2.0.2
      with:
        runtime: node@$24
        cache: true
