name: Install node & pnpm dependencies
description: Prepare repository and all dependencies

runs:
  using: composite
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: pnpm

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      id: pnpm-install
      with:
        version: latest
        run_install: false

    - name: Enable peerdeps auto-install
      shell: bash
      run: pnpm config set auto-install-peers true

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
